networks:
  database:
  broker:
services:
  local:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - database
      - broker
    profiles: ["local", "test"]
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=local_db
      - BROKER_DSN=amqp://guest:guest@broker:5672/
    depends_on:
      - database
      - broker
    entrypoint: ["go", "run", "cmd/server/main.go"]

  apitest:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - database
      - broker
    profiles: ["test"]
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=local_db
      - BROKER_DSN=amqp://guest:guest@broker:5672/
    depends_on:
      - database
      - broker

  database:
    image: postgres:latest
    profiles : ["local", "test"]
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=local_db
    ports:
      - "5432:5432"
    networks:
      - database

  broker:
    image: rabbitmq:latest
    profiles: ["local", "test"]
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
    networks:
      - broker
