networks:
  database:
services:
  apitest:
    build:
      context: .
      dockerfile: Dockerfile.apitest
    networks:
      - database
    profiles: ["test"]
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=local_db
    depends_on:
      - database

  database:
    image: postgres:latest
    profiles : ["test"]
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=local_db
    ports:
      - "5432:5432"
    networks:
      - database
